

CREATE TABLE users (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       firstname VARCHAR(255) not null ,
                       lastname VARCHAR(255) not null ,
                       username VARCHAR(255) unique not null,
                       password VARCHAR(255) not null ,
                       role VARCHAR(255)
);


CREATE TABLE doctors (
                         id INT AUTO_INCREMENT primary key,
                         name VARCHAR(255) not null,
                         bmdc VARCHAR(255) unique not null
);

CREATE TABLE patients (
                          id INT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255) not null ,
                          phone VARCHAR(20) unique not null,
                          age VARCHAR(255) not null
);

CREATE TABLE generics (
                          id INT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255) unique not null

);

CREATE TABLE vendors (
                         id INT AUTO_INCREMENT PRIMARY KEY,
                         name VARCHAR(255) not null
);


CREATE TABLE drugs (
                       id INT AUTO_INCREMENT PRIMARY KEY,
                       drug_name VARCHAR(255) not null ,
                       formula TEXT,
                       Strength TEXT,
                       generic_id INT,
                       vendor_id INT,
                       FOREIGN KEY (generic_id) REFERENCES generics(id),
                       FOREIGN KEY (vendor_id) REFERENCES vendors(id)
);


CREATE TABLE areas (
                           id INT AUTO_INCREMENT PRIMARY KEY,
                           name VARCHAR(255) unique not null ,
                           lat DOUBLE unique not null ,
                           lng DOUBLE unique not null,
                           district_id INT,
                           FOREIGN KEY (district_id) REFERENCES districts(id)

);


CREATE TABLE divisions (
                           id INT AUTO_INCREMENT PRIMARY KEY,
                           name VARCHAR(255) unique not null ,
                           lat DOUBLE unique not null ,
                           lng DOUBLE unique not null

);


CREATE TABLE districts (
                           id INT AUTO_INCREMENT PRIMARY KEY,
                           location_name VARCHAR(255) unique not null ,
                           latitude DOUBLE unique not null ,
                           longitude DOUBLE unique not null,
                           division_id INT,
                           FOREIGN KEY (division_id) REFERENCES divisions(id)
);



CREATE TABLE prescriptions (
                               id INT AUTO_INCREMENT PRIMARY KEY,
                               doctor_id INT,
                               patient_id INT,
                               location_id INT,
                               FOREIGN KEY (doctor_id) REFERENCES doctors(id),
                               FOREIGN KEY (patient_id) REFERENCES patients(id),
                               FOREIGN KEY (location_id) REFERENCES locations(id)
);





CREATE TABLE prescription_drugs (   id INT AUTO_INCREMENT PRIMARY KEY,
                                    prescription_id INT,
                                    drug_id INT,

                                    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
                                    FOREIGN KEY (drug_id) REFERENCES drugs(id)
);




INSERT INTO locations (location_name, latitude, longitude, division_id) VALUES
                                                                            ('Gulshan-1', 23.7806615, 90.4112899, 1),
                                                                            ('Banani', 23.7947552, 90.3954059, 1),
                                                                            ('Dhanmondi', 23.7470303, 90.3655623, 1),
                                                                            ('Mirpur-1', 23.7945624, 90.3435587, 1),
                                                                            ('Uttara', 23.8766322, 90.3576884, 1),
                                                                            ('Shahbag', 23.7348, 90.3929, 1),
                                                                            ('Mirpur', 23.8223, 90.3654, 1),
                                                                            ('Mohammadpur', 23.7639, 90.3610, 1),
                                                                            ('Farmgate', 23.7537, 90.3844, 1),
                                                                            ('Motijheel', 23.7345, 90.4146, 1),
                                                                            ('Karwan Bazar', 23.7503, 90.4005, 1),
                                                                            ('New Market', 23.7303, 90.4081, 1),
                                                                            ('Science Laboratory', 23.7368, 90.3779, 1),
                                                                            ('Lalbagh', 23.7115, 90.4088, 1),
                                                                            ('Badda', 23.7876, 90.4236, 1),
                                                                            ('Rampura', 23.7622, 90.4173, 1),
                                                                            ('Mohakhali', 23.7799, 90.4066, 1),
                                                                            ('Khilgaon', 23.7384, 90.4334, 1),
                                                                            ('Pallabi', 23.8313, 90.3632, 1),
                                                                            ('Banasree', 23.7740, 90.4335, 1),
                                                                            ('Baridhara', 23.8037, 90.4231, 1),
                                                                            ('Niketon', 23.7974, 90.4043, 1),
                                                                            ('Wari', 23.7154, 90.4035, 1),
                                                                            ('Jatrabari', 23.7191, 90.4557, 1),
                                                                            ('Mirpur DOHS', 23.8213, 90.3683, 1),
                                                                            ('Baily Road', 23.7294, 90.4023, 1),
                                                                            ('Mohakhali DOHS', 23.7993, 90.4082, 1),
                                                                            ('Shyamoli', 23.7607, 90.3714, 1 ),
                                                                            ('Banglamotor', 23.7486, 90.3852, 1),
                                                                            ('Malibagh', 23.7484, 90.4290, 1),
                                                                            ('Rampura Bridge', 23.7593, 90.4272, 1),
                                                                            ('Hazaribagh', 23.7247, 90.4167, 1),
                                                                            ('Azimpur', 23.7211, 90.3880, 1),
                                                                            ('Tejgaon', 23.7617, 90.4064, 1),
                                                                            ('Kamalapur', 23.7313, 90.4164, 1),
                                                                            ('Agargaon', 23.7753, 90.3715, 1),
                                                                            ('Mirpur-10', 23.8129, 90.3630, 1),
                                                                            ('Mirpur-2', 23.8052, 90.3656, 1),
                                                                            ('Mohammadpur Town Hall', 23.7678, 90.3606, 1),
                                                                            ('Mohammadpur Bus Stand', 23.7651, 90.3624, 1),
                                                                            ('Kalabagan', 23.7494, 90.3748, 1),
                                                                            ('Shantinagar', 23.7311, 90.4178, 1),
                                                                            ('Hatirpool', 23.7443, 90.3926, 1),
                                                                            ('Mohakhali Bus Stand', 23.7889, 90.4080, 1),
                                                                            ('Bongshal', 23.7151, 90.4093, 1),
                                                                            ('Gulistan', 23.7226, 90.4165, 1),
                                                                            ('Malibagh Railgate', 23.7523, 90.4292, 1),
                                                                            ('Malibagh Mor', 23.7546, 90.4228, 1),
                                                                            ('Kuril Biswa Road', 23.8056, 90.4254, 1),
                                                                            ('Dhaka', 23.7115253, 90.4111451, 1),
                                                                            ('Faridpur', 23.6070822, 89.8429406, 1),
                                                                            ('Gazipur', 24.0022858, 90.4264283, 1),
                                                                            ('Gopalganj', 23.0050857, 89.8266059, 1),
                                                                            ('Jamalpur', 24.937533, 89.937775, 7),
                                                                            ('Kishoreganj', 24.444937, 90.776575, 1),
                                                                            ('Madaripur', 23.164102, 90.1896805, 1),
                                                                            ('Manikganj', 23.8644, 90.0047, 1),
                                                                            ('Munshiganj', 23.5422, 90.5305, 1),
                                                                            ('Mymensingh', 24.7471, 90.4203, 7),
                                                                            ('Narayanganj', 23.63366, 90.496482, 1),
                                                                            ('Narsingdi', 23.932233, 90.71541, 1),
                                                                            ('Netrokona', 24.870955, 90.727887, 7),
                                                                            ('Rajbari', 23.7574305, 89.6444665, 1),
                                                                            ('Shariatpur', 23.2423, 90.4348, 1),
                                                                            ('Sherpur', 25.0204933, 90.0152966, 7),
                                                                            ('Tangail', 24.2513, 89.9167, 1),
                                                                            ('Bogura', 24.8465228, 89.377755, 5),
                                                                            ('Joypurhat', 25.0968, 89.0227, 5),
                                                                            ('Naogaon', 24.7936, 88.9318, 5),
                                                                            ('Natore', 24.420556, 89.000282, 5),
                                                                            ('Nawabganj', 24.5965034, 88.2775122, 1),
                                                                            ('Pabna', 23.998524, 89.233645, 5),
                                                                            ('Rajshahi', 24.3745, 88.6042, 5),
                                                                            ('Sirajgonj', 24.4533978, 89.7006815, 5),
                                                                            ('Dinajpur', 25.6217061, 88.6354504, 6),
                                                                            ('Gaibandha', 25.328751, 89.528088, 6),
                                                                            ('Kurigram', 25.805445, 89.636174, 6),
                                                                            ('Lalmonirhat', 25.9923, 89.2847, 6),
                                                                            ('Nilphamari', 25.931794, 88.856006, 6),
                                                                            ('Panchagarh', 26.3411, 88.5541606, 6),
                                                                            ('Rangpur', 25.7558096, 89.244462, 6),
                                                                            ('Thakurgaon', 26.0336945, 88.4616834, 6),
                                                                            ('Barguna', 22.0953, 90.1121, 4),
                                                                            ('Barishal', 22.7010, 90.3535, 4),
                                                                            ('Bhola', 22.685923, 90.648179, 4),
                                                                            ('Jhalokati', 22.6406, 90.1987, 4),
                                                                            ('Patuakhali', 22.3596316, 90.3298712, 4),
                                                                            ('Pirojpur', 22.5841, 89.9720, 4),
                                                                            ('Bandarban', 22.1953275, 92.2183773, 2),
                                                                            ('Brahmanbaria', 23.9570904, 91.1119286, 2),
                                                                            ('Chandpur', 23.2332585, 90.6712912, 2),
                                                                            ('Chattogram', 22.335109, 91.834073, 2),
                                                                            ('Cumilla', 23.4682747, 91.1788135, 2),
                                                                            ('Cox''s Bazar', 21.4272, 92.0058, 2),
                                                                            ('Feni', 23.0159, 91.3976, 2),
                                                                            ('Khagrachari', 23.119285, 91.984663, 2),
                                                                            ('Lakshmipur', 22.942477, 90.841184, 2),
                                                                            ('Noakhali', 22.869563, 91.099398, 2),
                                                                            ('Rangamati', 22.7324, 92.2985, 2),
                                                                            ('Habiganj', 24.374945, 91.41553, 8),
                                                                            ('Maulvibazar', 24.482934, 91.777417, 8),
                                                                            ('Sunamganj', 25.0658042, 91.3950115, 8),
                                                                            ('Sylhet', 24.8897956, 91.8697894, 8),
                                                                            ('Bagerhat', 22.651568, 89.785938, 3),
                                                                            ('Chuadanga', 23.6401961, 88.841841, 3),
                                                                            ('Jashore', 23.16643, 89.2081126, 3),
                                                                            ('Jhenaidah', 23.5448176, 89.1539213, 3),
                                                                            ('Khulna', 22.815774, 89.568679, 3),
                                                                            ('Kushtia', 23.901258, 89.120482,3 ),
                                                                            ('Magura', 23.487337, 89.419956, 3),
                                                                            ('Meherpur', 23.762213, 88.631821, 3),
                                                                            ('Narail', 23.172534, 89.512672, 3),
                                                                            ('Satkhira', 22.7185, 89.0705, 3);


INSERT INTO divisions (name, lat, lng) VALUES ('DHAKA', 23.80752056124966, 90.41590901066833),
                                              ('CHITTAGONG', 22.38023381039401, 91.82967658593265),
                                              ('KHULNA', 22.839654595743053, 89.5408447098732),
                                              ('BARISHAL', 22.71399526448547, 90.34897572477993),
                                              ('RAJSHAHI', 24.377553558066847, 88.6037560363994),
                                              ('RANGPUR', 25.751651725195643, 89.26200855373632),
                                              ('MYMENSINGH', 24.746690537025774, 90.41863531617815),
                                              ('SYLHET', 24.90667560424398, 91.86172139418804);




INSERT INTO generics (name) VALUES
                                ('Aceclofenac'),
                                ('Ambroxol-Hydrochloride'),
                                ('Amlodipine-Besylate'),
                                ('Amlodipine-Besylate-+-Atenolol'),
                                ('Amlodipine-+-Telmisartan'),
                                ('Amoxicillin-+-Clavulanic-Acid'),
                                ('Atorvastatin'),
                                ('Azithromycin'),
                                ('Baclofen'),
                                ('Bilastine'),
                                ('Bisoprolol'),
                                ('Butamirate-Citrate'),
                                ('Calcium-Carbonate-&-vitamin-D3'),
                                ('Calcium-(Coral-source)-+-Vitamin-D3'),
                                ('Calcium-Orotate'),
                                ('Carbonyl-Iron_Folic-Acid_Zinc-Sulphate'),
                                ('Cefepime');




INSERT INTO vendors (name) VALUES
                               ('ACI-Limited'),
                               ('ACME-Laboratories-Ltd'),
                               ('Ad-din-Pharmaceuticals-Ltd'),
                               ('Aexim-Pharmaceuticals-Ltd'),
                               ('Al-Madina-Pharmaceuticals-Ltd'),
                               ('Albion-Laboratories-Limited'),
                               ('Alco-Pharma-Ltd'),
                               ('Alien-Pharma'),
                               ('Alkad-Laboratories'),
                               ('Allied-Pharmaceuticals-Ltd'),
                               ('Ambee-Pharmaceuticals-Ltd'),
                               ('Amico-Laboratories-Ltd'),
                               ('Amulet-Pharmaceuticals-Ltd'),
                               ('APC-Pharma-Ltd');



INSERT INTO doctors (name, bmdc) VALUES
                                     ('Dr. Ashraful Islam', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Zahid Hossain', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Omar Ahmed', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Rafi Khan', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Anwar Ali', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Alam Rahman', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Shahid Karim', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Rubel Uddin', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Reza Miah', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000),
                                     ('Dr. Hasan Chowdhury', FLOOR(RAND() * (9999 - 1000 + 1)) + 1000);

INSERT INTO patients (name, phone, age)
VALUES
    ('John Doe', '01234567890', '55'),
    ('Alice Smith', '09876543210','25'),
    ('Bob Johnson', '05551234567','36'),
    ('Emily Brown', '05559876543','88'),
    ('Michael Wilson', '09998887776','63'),
    ('Emma Lee', '01239874560','55'),
    ('William Taylor', '07894561230','40'),
    ('Olivia Martinez', '09517534680','52'),
    ('James Anderson', '04561237890','93'),
    ('Sophia Garcia', '03692581470','27'),
    ('Alexander Hernandez', '07539518520','45'),
    ('Mia Lopez', '03216549870','27'),
    ('Ethan Perez', '06543219870','33'),
    ('Charlotte Gonzalez', '02589631470','45'),
    ('Daniel Ramirez', '07896541230','60'),
    ('Amelia Torres', '09638527410','70'),
    ('Matthew Flores', '01472583690','90'),
    ('Harper Diaz', '01593578520','90'),
    ('Henry Rivera', '03579514560','61'),
    ('Ava Cruz', '08529637410','99');



INSERT INTO doctors (name, bmdc) VALUES
                                     ('Dr. Ashraful Islam', 1022),
                                     ('Dr. Nafis Rahman', 1023),
                                     ('Dr. Ayesha Siddiqui', 1024),
                                     ('Dr. Omar Farooq', 1025),
                                     ('Dr. Rehana Begum', 1026),
                                     ('Dr. Tahmid Karim', 1027),
                                     ('Dr. Nusrat Jahan', 1028),
                                     ('Dr. Hasan Mahmud', 1029),
                                     ('Dr. Kamal Ahmed', 1030),
                                     ('Dr. Saima Chowdhury', 1031),
                                     ('Dr. Ashraful Islam', 1032),
                                     ('Dr. Nafis Rahma', 1033),
                                     ('Dr. Ayesha Siddiqui', 1034),
                                     ('Dr. Omar Farooq', 1035),
                                     ('Dr. Rehana Begum', 1036),
                                     ('Dr. Tahmid Karim', 1037),
                                     ('Dr. Nusrat Jahan', 1038),
                                     ('Dr. Hasan Mahmud', 1039),
                                     ('Dr. Kamal Ahmed', 1040),
                                     ('Dr. Saima Chowdhury', 1041),
                                     ('Dr. Ashraful Islam', 1042),
                                     ('Dr. Nafis Rahman', 1043),
                                     ('Dr. Ayesha Siddiqu', 1044),
                                     ('Dr. Omar Farooq', 1045),
                                     ('Dr. Rehana Begum', 1046),
                                     ('Dr. Tahmid Karim', 1047),
                                     ('Dr. Nusrat Jahan', 1048),
                                     ('Dr. Hasan Mahmud', 1049),
                                     ('Dr. Kamal Ahmed', 1050);





INSERT INTO drugs (drug_name, formula, strength, generic_id, vendor_id)VALUES
                                                                           ('Ibuprofen', 'Tablet', '200mg', 1, 1),
                                                                           ('Amoxicillin', 'Capsule', '500mg', 2, 2),
                                                                           ('Cetirizine', 'Liquid', '5mg/5ml', 3, 3),
                                                                           ('Insulin Glargine', 'Injection', '100U/ml', 4, 4),
                                                                           ('Clotrimazole', 'Cream', '1%', 5, 5),
                                                                           ('Hydrocortisone', 'Ointment', '2.5%', 6, 6),
                                                                           ('Metformin', 'Tablet', '500mg', 7, 7),
                                                                           ('Omeprazole', 'Capsule', '20mg', 8, 8),
                                                                           ('Salbutamol', 'Inhaler', '100mcg', 9, 9),
                                                                           ('Loratadine', 'Syrup', '5mg/5ml', 10, 10),
                                                                           ('Paracetamol', 'Tablet', '500mg', 11, 11),
                                                                           ('Aspirin', 'Tablet', '81mg', 12, 1),
                                                                           ('Azithromycin', 'Tablet', '250mg', 13, 2),
                                                                           ('Doxycycline', 'Capsule', '100mg', 14, 3),
                                                                           ('Furosemide', 'Injection', '10mg/ml', 15, 4),
                                                                           ('Gabapentin', 'Tablet', '300mg', 16, 5),
                                                                           ('Lisinopril', 'Tablet', '10mg', 17, 6),
                                                                           ('Montelukast', 'Tablet', '10mg', 18, 7),
                                                                           ('Prednisolone', 'Liquid', '15mg/5ml', 19, 8),
                                                                           ('Ranitidine', 'Tablet', '150mg', 20, 9),
                                                                           ('Simvastatin', 'Tablet', '20mg', 1, 10),
                                                                           ('Amlodipine', 'Tablet', '5mg', 2, 11),
                                                                           ('Ciprofloxacin', 'Tablet', '500mg', 3, 1),
                                                                           ('Fluconazole', 'Capsule', '150mg', 4, 2),
                                                                           ('Ibuprofen', 'Suspension', '100mg/5ml', 5, 3),
                                                                           ('Metronidazole', 'Tablet', '400mg', 6, 4),
                                                                           ('Tramadol', 'Capsule', '50mg', 7, 5),
                                                                           ('Duloxetine', 'Capsule', '30mg', 8, 6),
                                                                           ('Gabapentin', 'Capsule', '300mg', 9, 7),
                                                                           ('Levothyroxine', 'Tablet', '50mcg', 10, 8),
                                                                           ('Metformin', 'Tablet', '850mg', 11, 9),
                                                                           ('Naprosyn', 'Tablet', '500mg', 12, 10),
                                                                           ('Sildenafil', 'Tablet', '50mg', 13, 11),
                                                                           ('Tadalafil', 'Tablet', '5mg', 14, 1),
                                                                           ('Atorvastatin', 'Tablet', '10mg', 15, 2),
                                                                           ('Diclofenac', 'Gel', '1%', 16, 3),
                                                                           ('Esomeprazole', 'Tablet', '40mg', 17, 4),
                                                                           ('Folic Acid', 'Tablet', '5mg', 18, 5),
                                                                           ('Glyburide', 'Tablet', '5mg', 19, 6),
                                                                           ('Hydrochlorothiazide', 'Tablet', '25mg', 20, 7),
                                                                           ('Ivermectin', 'Tablet', '3mg', 1, 8),
                                                                           ('Lamotrigine', 'Tablet', '100mg', 2, 9),
                                                                           ('Methylphenidate', 'Tablet', '10mg', 3, 10),
                                                                           ('Nitrofurantoin', 'Capsule', '100mg', 4, 11),
                                                                           ('Ondansetron', 'Tablet', '8mg', 5, 1),
                                                                           ('Pantoprazole', 'Tablet', '40mg', 6, 2),
                                                                           ('Quetiapine', 'Tablet', '25mg', 7, 3),
                                                                           ('Rosuvastatin', 'Tablet', '10mg', 8, 4),
                                                                           ('Sertraline', 'Tablet', '50mg', 9, 5),
                                                                           ('Topiramate', 'Tablet', '25mg', 10, 6),
                                                                           ('Valacyclovir', 'Tablet', '500mg', 11, 7),
                                                                           ('Warfarin', 'Tablet', '5mg', 12, 8),
                                                                           ('Xarelto', 'Tablet', '20mg', 13, 9),
                                                                           ('Yasmin', 'Tablet', '3mg', 14, 10),
                                                                           ('Zolpidem', 'Tablet', '10mg', 15, 11),
                                                                           ('Acetaminophen', 'Tablet', '325mg', 16, 1),
                                                                           ('Benazepril', 'Tablet', '10mg', 17, 2),
                                                                           ('Candesartan', 'Tablet', '16mg', 18, 3),
                                                                           ('Desloratadine', 'Tablet', '5mg', 19, 4),
                                                                           ('Erythromycin', 'Tablet', '500mg', 20, 5),
                                                                           ('Fluoxetine', 'Capsule', '20mg', 1, 6),
                                                                           ('Glipizide', 'Tablet', '10mg', 2, 7),
                                                                           ('Hydroxychloroquine', 'Tablet', '200mg', 3, 8),
                                                                           ('Indomethacin', 'Capsule', '25mg', 4, 9),
                                                                           ('Januvia', 'Tablet', '100mg', 5, 10),
                                                                           ('Keppra', 'Tablet', '500mg', 6, 11),
                                                                           ('Levofloxacin', 'Tablet', '500mg', 7, 1),
                                                                           ('Methotrexate', 'Tablet', '2.5mg', 8, 2),
                                                                           ('Naproxen', 'Tablet', '250mg', 9, 3),
                                                                           ('Olanzapine', 'Tablet', '10mg', 10, 4),
                                                                           ('Propranolol', 'Tablet', '40mg', 11, 5),
                                                                           ('Quinapril', 'Tablet', '20mg', 12, 6),
                                                                           ('Risperidone', 'Tablet', '1mg', 13, 7),
                                                                           ('Spironolactone', 'Tablet', '25mg', 14, 8),
                                                                           ('Trazodone', 'Tablet', '50mg', 15, 9),
                                                                           ('Ursodiol', 'Capsule', '250mg', 16, 10),
                                                                           ('Vardenafil', 'Tablet', '10mg', 17, 11),
                                                                           ('Wellbutrin', 'Tablet', '150mg', 18, 1),
                                                                           ('Xanax', 'Tablet', '0.5mg', 19, 2),
                                                                           ('Yohimbine', 'Tablet', '5mg', 20, 3),
                                                                           ('Zithromax', 'Tablet', '500mg', 1, 4);


INSERT INTO prescriptions (doctor_id, patient_id, location_id) VALUES
                                                                   (1, 1, 1),
                                                                   (1, 2, 2),
                                                                   (1, 3, 3),
                                                                   (1, 4, 4),
                                                                   (1, 5, 5),
                                                                   (2, 6, 6),
                                                                   (2, 7, 7),
                                                                   (2, 8, 8),
                                                                   (2, 9, 9),
                                                                   (2, 10, 10),
                                                                   (3, 11, 11),
                                                                   (3, 12, 12),
                                                                   (3, 13, 13),
                                                                   (3, 14, 14),
                                                                   (3, 15, 15),
                                                                   (4, 16, 16),
                                                                   (4, 17, 17),
                                                                   (4, 18, 18),
                                                                   (4, 19, 19),
                                                                   (4, 20, 20),
                                                                   (5, 21, 21),
                                                                   (5, 22, 22),
                                                                   (5, 23, 23),
                                                                   (5, 24, 24),
                                                                   (5, 25, 25),
                                                                   (6, 26, 26),
                                                                   (6, 27, 27),
                                                                   (6, 28, 28),
                                                                   (6, 29, 29),
                                                                   (6, 30, 30),
                                                                   (7, 31, 31),
                                                                   (7, 32, 32),
                                                                   (7, 33, 33),
                                                                   (7, 34, 34),
                                                                   (7, 35, 35),
                                                                   (8, 36, 36),
                                                                   (8, 37, 37),
                                                                   (8, 38, 38),
                                                                   (8, 39, 39),
                                                                   (8, 40, 40),
                                                                   (9, 41, 41),
                                                                   (9, 42, 42),
                                                                   (9, 43, 43),
                                                                   (9, 44, 44),
                                                                   (9, 45, 45),
                                                                   (10, 46, 46),
                                                                   (10, 47, 47),
                                                                   (10, 48, 48),
                                                                   (10, 49, 49),
                                                                   (10, 50, 50),
                                                                   (11, 1, 51),
                                                                   (11, 2, 52),
                                                                   (11, 3, 53),
                                                                   (11, 4, 54),
                                                                   (11, 5, 55),
                                                                   (12, 6, 56),
                                                                   (12, 7, 57),
                                                                   (12, 8, 58),
                                                                   (12, 9, 59),
                                                                   (12, 10, 60),
                                                                   (13, 11, 61),
                                                                   (13, 12, 62),
                                                                   (13, 13, 63),
                                                                   (13, 14, 64),
                                                                   (13, 15, 1),
                                                                   (14, 16, 2),
                                                                   (14, 17, 3),
                                                                   (14, 18, 4),
                                                                   (14, 19, 5),
                                                                   (14, 20, 6),
                                                                   (15, 21, 7),
                                                                   (15, 22, 8),
                                                                   (15, 23, 9),
                                                                   (15, 24, 10),
                                                                   (15, 25, 11),
                                                                   (16, 26, 12),
                                                                   (16, 27, 13),
                                                                   (16, 28, 14),
                                                                   (16, 29, 15),
                                                                   (16, 30, 16),
                                                                   (17, 31, 17),
                                                                   (17, 32, 18),
                                                                   (17, 33, 19),
                                                                   (17, 34, 20),
                                                                   (17, 35, 21),
                                                                   (18, 36, 22),
                                                                   (18, 37, 23),
                                                                   (18, 38, 24),
                                                                   (18, 39, 25),
                                                                   (18, 40, 26),
                                                                   (19, 41, 27),
                                                                   (19, 42, 28),
                                                                   (19, 43, 29),
                                                                   (19, 44, 30),
                                                                   (19, 45, 31),
                                                                   (20, 46, 32),
                                                                   (20, 47, 33),
                                                                   (20, 48, 34),
                                                                   (20, 49, 35),
                                                                   (20, 50, 36),
                                                                   (21, 1, 37),
                                                                   (21, 2, 38),
                                                                   (21, 3, 39),
                                                                   (21, 4, 40),
                                                                   (21, 5, 41),
                                                                   (22, 6, 42),
                                                                   (22, 7, 43),
                                                                   (22, 8, 44),
                                                                   (22, 9, 45),
                                                                   (22, 10, 46),
                                                                   (23, 11, 47),
                                                                   (23, 12, 48),
                                                                   (23, 13, 49),
                                                                   (23, 14, 50),
                                                                   (23, 15, 51),
                                                                   (24, 16, 52),
                                                                   (24, 17, 53),
                                                                   (24, 18, 54),
                                                                   (24, 19, 55),
                                                                   (24, 20, 56),
                                                                   (25, 21, 57),
                                                                   (25, 22, 58),
                                                                   (25, 23, 59),
                                                                   (25, 24, 60),
                                                                   (25, 25, 61),
                                                                   (26, 26, 62),
                                                                   (26, 27, 63),
                                                                   (26, 28, 64),
                                                                   (26, 29, 1),
                                                                   (26, 30, 2),
                                                                   (27, 31, 3),
                                                                   (27, 32, 4),
                                                                   (27, 33, 5),
                                                                   (27, 34, 6),
                                                                   (27, 35, 7),
                                                                   (28, 36, 8),
                                                                   (28, 37, 9),
                                                                   (28, 38, 10),
                                                                   (28, 39, 11),
                                                                   (28, 40, 12),
                                                                   (29, 41, 13),
                                                                   (29, 42, 14),
                                                                   (29, 43, 15),
                                                                   (29, 44, 16),
                                                                   (29, 45, 17),
                                                                   (30, 46, 18),
                                                                   (30, 47, 19),
                                                                   (30, 48, 20),
                                                                   (30, 49, 21),
                                                                   (30, 50, 22),
                                                                   (31, 1, 23),
                                                                   (31, 2, 24),
                                                                   (31, 3, 25),
                                                                   (31, 4, 26),
                                                                   (31, 5, 27),
                                                                   (32, 6, 28),
                                                                   (32, 7, 29),
                                                                   (32, 8, 30),
                                                                   (32, 9, 31),
                                                                   (32, 10, 32),
                                                                   (33, 11, 33),
                                                                   (33, 12, 34),
                                                                   (33, 13, 35),
                                                                   (33, 14, 36),
                                                                   (33, 15, 37),
                                                                   (34, 16, 38),
                                                                   (34, 17, 39),
                                                                   (34, 18, 40),
                                                                   (34, 19, 41),
                                                                   (34, 20, 42),
                                                                   (35, 21, 43),
                                                                   (35, 22, 44),
                                                                   (35, 23, 45),
                                                                   (35, 24, 46),
                                                                   (35, 25, 47),
                                                                   (36, 26, 48),
                                                                   (36, 27, 49),
                                                                   (36, 28, 50),
                                                                   (36, 29, 51),
                                                                   (36, 30, 52),
                                                                   (37, 31, 53),
                                                                   (37, 32, 54),
                                                                   (37, 33, 55),
                                                                   (37, 34, 56),
                                                                   (37, 35, 57),
                                                                   (38, 36, 58),
                                                                   (38, 37, 59),
                                                                   (38, 38, 60),
                                                                   (38, 39, 61),
                                                                   (38, 40, 62),
                                                                   (39, 41, 63),
                                                                   (39, 42, 64),
                                                                   (39, 43, 1),
                                                                   (39, 44, 2),
                                                                   (39, 45, 3),
                                                                   (40, 46, 4),
                                                                   (40, 47, 5),
                                                                   (40, 48, 6),
                                                                   (40, 49, 7),
                                                                   (40, 50, 8);

INSERT INTO prescription_drugs (prescription_id, drug_id) VALUES
                                                              (1, 1),
                                                              (1, 2),
                                                              (1, 3),
                                                              (2, 4),
                                                              (2, 5),
                                                              (2, 6),
                                                              (3, 7),
                                                              (3, 8),
                                                              (3, 9),
                                                              (4, 10),
                                                              (4, 11),
                                                              (4, 12),
                                                              (5, 13),
                                                              (5, 14),
                                                              (5, 15),
                                                              (6, 16),
                                                              (6, 17),
                                                              (6, 18),
                                                              (7, 19),
                                                              (7, 20),
                                                              (7, 21),
                                                              (8, 22),
                                                              (8, 23),
                                                              (8, 24),
                                                              (9, 25),
                                                              (9, 26),
                                                              (9, 27),
                                                              (10, 28),
                                                              (10, 29),
                                                              (10, 30),
                                                              (11, 31),
                                                              (11, 32),
                                                              (11, 33),
                                                              (12, 34),
                                                              (12, 35),
                                                              (12, 36),
                                                              (13, 37),
                                                              (13, 38),
                                                              (13, 39),
                                                              (14, 40),
                                                              (14, 41),
                                                              (14, 42),
                                                              (15, 43),
                                                              (15, 44),
                                                              (15, 45),
                                                              (16, 46),
                                                              (16, 47),
                                                              (16, 48),
                                                              (17, 49),
                                                              (17, 50),
                                                              (17, 51),
                                                              (18, 52),
                                                              (18, 53),
                                                              (18, 54),
                                                              (19, 55),
                                                              (19, 56),
                                                              (19, 57),
                                                              (20, 58),
                                                              (20, 59),
                                                              (20, 60),
                                                              (21, 61),
                                                              (21, 62),
                                                              (21, 63),
                                                              (22, 64),
                                                              (22, 65),
                                                              (22, 66),
                                                              (23, 67),
                                                              (23, 68),
                                                              (23, 69),
                                                              (24, 70),
                                                              (24, 71),
                                                              (24, 72),
                                                              (25, 73),
                                                              (25, 74),
                                                              (25, 75),
                                                              (26, 76),
                                                              (26, 77),
                                                              (26, 78),
                                                              (27, 79),
                                                              (27, 80),
                                                              (27, 81),
                                                              (28, 82),
                                                              (28, 83),
                                                              (28, 84),
                                                              (29, 85),
                                                              (29, 86),
                                                              (30, 1),
                                                              (30, 4),
                                                              (30, 7),
                                                              (31, 10),
                                                              (31, 13),
                                                              (31, 16),
                                                              (32, 19),
                                                              (32, 22),
                                                              (32, 25),
                                                              (33, 28),
                                                              (33, 31),
                                                              (33, 34),
                                                              (34, 37),
                                                              (34, 40),
                                                              (34, 43),
                                                              (35, 46),
                                                              (35, 49),
                                                              (35, 52),
                                                              (36, 55),
                                                              (36, 58),
                                                              (36, 61),
                                                              (37, 64),
                                                              (37, 67),
                                                              (37, 70),
                                                              (38, 73),
                                                              (38, 76),
                                                              (38, 79),
                                                              (39, 82),
                                                              (39, 85),
                                                              (2, 2),
                                                              (2, 5),
                                                              (2, 8),
                                                              (3, 11),
                                                              (3, 14),
                                                              (3, 17),
                                                              (4, 20),
                                                              (4, 23),
                                                              (4, 26),
                                                              (5, 29),
                                                              (5, 32),
                                                              (5, 35),
                                                              (6, 38),
                                                              (6, 41),
                                                              (6, 44),
                                                              (7, 47),
                                                              (7, 50),
                                                              (7, 53),
                                                              (8, 56),
                                                              (8, 59),
                                                              (8, 62),
                                                              (9, 65),
                                                              (9, 68),
                                                              (9, 71),
                                                              (10, 74),
                                                              (10, 77),
                                                              (10, 80),
                                                              (11, 83),
                                                              (11, 86),
                                                              (12, 1),
                                                              (12, 4),
                                                              (12, 7),
                                                              (13, 10),
                                                              (13, 13),
                                                              (13, 16),
                                                              (14, 19),
                                                              (14, 22),
                                                              (14, 25),
                                                              (15, 28),
                                                              (15, 31),
                                                              (15, 34),
                                                              (16, 37),
                                                              (16, 40),
                                                              (16, 43),
                                                              (17, 46),
                                                              (17, 49),
                                                              (17, 52),
                                                              (18, 55),
                                                              (18, 58),
                                                              (18, 61),
                                                              (19, 64),
                                                              (19, 67),
                                                              (19, 70),
                                                              (20, 73),
                                                              (20, 76),
                                                              (20, 79),
                                                              (21, 82),
                                                              (21, 85),
                                                              (22, 2),
                                                              (22, 5),
                                                              (22, 8),
                                                              (23, 11),
                                                              (23, 14),
                                                              (23, 17),
                                                              (24, 20),
                                                              (24, 23),
                                                              (24, 26),
                                                              (25, 29),
                                                              (25, 32),
                                                              (25, 35),
                                                              (26, 38),
                                                              (26, 41),
                                                              (26, 44),
                                                              (27, 47),
                                                              (27, 50),
                                                              (27, 53),
                                                              (28, 56),
                                                              (28, 59),
                                                              (28, 62),
                                                              (29, 65),
                                                              (29, 68),
                                                              (29, 71),
                                                              (30, 74),
                                                              (30, 77),
                                                              (30, 80),
                                                              (31, 83),
                                                              (31, 86),
                                                              (40, 1),
                                                              (41, 2),
                                                              (42, 3),
                                                              (43, 4),
                                                              (44, 5),
                                                              (45, 6),
                                                              (46, 7),
                                                              (47, 8),
                                                              (48, 9),
                                                              (49, 10),
                                                              (50, 11),
                                                              (51, 12),
                                                              (52, 13),
                                                              (53, 14),
                                                              (54, 15),
                                                              (55, 16),
                                                              (56, 17),
                                                              (57, 18),
                                                              (58, 19),
                                                              (59, 20),
                                                              (60, 21),
                                                              (61, 22),
                                                              (62, 23),
                                                              (63, 24),
                                                              (64, 25),
                                                              (65, 26),
                                                              (66, 27),
                                                              (67, 28),
                                                              (68, 29),
                                                              (69, 30),
                                                              (70, 31),
                                                              (71, 32),
                                                              (72, 33),
                                                              (73, 34),
                                                              (74, 35),
                                                              (75, 36),
                                                              (76, 37),
                                                              (77, 38),
                                                              (78, 39),
                                                              (79, 40),
                                                              (80, 41),
                                                              (81, 42),
                                                              (82, 43),
                                                              (83, 44),
                                                              (84, 45),
                                                              (85, 46),
                                                              (86, 47),
                                                              (87, 48),
                                                              (88, 49),
                                                              (89, 50),
                                                              (90, 51),
                                                              (91, 52),
                                                              (92, 53),
                                                              (93, 54),
                                                              (94, 55),
                                                              (95, 56),
                                                              (96, 57),
                                                              (97, 58),
                                                              (98, 59),
                                                              (99, 60),
                                                              (100, 61),
                                                              (101, 62),
                                                              (102, 63),
                                                              (103, 64),
                                                              (104, 65),
                                                              (105, 66),
                                                              (106, 67),
                                                              (107, 68),
                                                              (108, 69),
                                                              (109, 70),
                                                              (110, 71),
                                                              (111, 72),
                                                              (112, 73),
                                                              (113, 74),
                                                              (114, 75),
                                                              (115, 76),
                                                              (116, 77),
                                                              (117, 78),
                                                              (118, 79),
                                                              (119, 80),
                                                              (120, 81),
                                                              (121, 82),
                                                              (122, 83),
                                                              (123, 84),
                                                              (124, 85),
                                                              (125, 86),
                                                              (126, 1),
                                                              (127, 2),
                                                              (128, 3),
                                                              (129, 4),
                                                              (130, 5),
                                                              (131, 6),
                                                              (132, 7),
                                                              (133, 8),
                                                              (134, 9),
                                                              (135, 10),
                                                              (136, 11),
                                                              (137, 12),
                                                              (138, 13),
                                                              (139, 14),
                                                              (140, 15),
                                                              (141, 16),
                                                              (142, 17),
                                                              (143, 18),
                                                              (144, 19),
                                                              (145, 20),
                                                              (146, 21),
                                                              (147, 22),
                                                              (148, 23),
                                                              (149, 24),
                                                              (150, 25),
                                                              (151, 26),
                                                              (152, 27),
                                                              (153, 28),
                                                              (154, 29),
                                                              (155, 30),
                                                              (156, 31),
                                                              (157, 32),
                                                              (158, 33),
                                                              (159, 34),
                                                              (160, 35),
                                                              (161, 36),
                                                              (162, 37),
                                                              (163, 38),
                                                              (164, 39),
                                                              (165, 40),
                                                              (166, 41),
                                                              (167, 42),
                                                              (168, 43),
                                                              (169, 44),
                                                              (170, 45),
                                                              (171, 46),
                                                              (172, 47),
                                                              (173, 48),
                                                              (174, 49),
                                                              (175, 50),
                                                              (176, 51),
                                                              (177, 52),
                                                              (178, 53),
                                                              (179, 54),
                                                              (180, 55),
                                                              (181, 56),
                                                              (182, 57),
                                                              (183, 58),
                                                              (184, 59),
                                                              (185, 60),
                                                              (186, 61),
                                                              (187, 62),
                                                              (188, 63),
                                                              (189, 64),
                                                              (190, 65),
                                                              (191, 66),
                                                              (192, 67),
                                                              (193, 68),
                                                              (194, 69),
                                                              (195, 70),
                                                              (196, 71),
                                                              (197, 72),
                                                              (198, 73),
                                                              (199, 74),
                                                              (200, 75);


INSERT INTO doctors (name, bmdc) VALUES
                                     ('Dr. Ashraful Islam', 1022),
                                     ('Dr. Nafis Rahman', 1023),
                                     ('Dr. Ayesha Siddiqui', 1024),
                                     ('Dr. Omar Farooq', 1025),
                                     ('Dr. Rehana Begum', 1026),
                                     ('Dr. Tahmid Karim', 1027),
                                     ('Dr. Nusrat Jahan', 1028),
                                     ('Dr. Hasan Mahmud', 1029),
                                     ('Dr. Kamal Ahmed', 1030),
                                     ('Dr. Saima Chowdhury', 1031),
                                     ('Dr. Ashraful Islam', 1032),
                                     ('Dr. Nafis Rahma', 1033),
                                     ('Dr. Ayesha Siddiqui', 1034),
                                     ('Dr. Omar Farooq', 1035),
                                     ('Dr. Rehana Begum', 1036),
                                     ('Dr. Tahmid Karim', 1037),
                                     ('Dr. Nusrat Jahan', 1038),
                                     ('Dr. Hasan Mahmud', 1039),
                                     ('Dr. Kamal Ahmed', 1040),
                                     ('Dr. Saima Chowdhury', 1041),
                                     ('Dr. Ashraful Islam', 1042),
                                     ('Dr. Nafis Rahman', 1043),
                                     ('Dr. Ayesha Siddiqu', 1044),
                                     ('Dr. Omar Farooq', 1045),
                                     ('Dr. Rehana Begum', 1046),
                                     ('Dr. Tahmid Karim', 1047),
                                     ('Dr. Nusrat Jahan', 1048),
                                     ('Dr. Hasan Mahmud', 1049),
                                     ('Dr. Kamal Ahmed', 1050);





SELECT DISTINCT  d.name, d.bmdc
FROM prescriptions p
         JOIN locations l ON p.location_id = l.id
         JOIN doctors d ON p.doctor_id = d.bmdc
WHERE l.location_name = 'Banani';



/*    @Query("SELECT COUNT(p) FROM Prescription p JOIN p.drugs d JOIN p.area l WHERE d.drugName LIKE %:drugName% AND l.locationName LIKE %:locationName%")
    Long countPrescriptionsByDrugNameAndLocationName(@Param("drugName") String drugName, @Param("locationName") String locationName);*/
